userwidgets/ui

package-lock.json
package.json
src/Client.ts
src/State/Applications.ts
src/State/Me.ts
src/State/Organizations.ts
src/State/Users.ts
src/State/index.ts
src/client.ts
src/components/demo/index.tsx
src/components/user/change-name/index.tsx
src/components/user/change-password/index.tsx
src/components/user/set-password/index.tsx

Depends on: https://github.com/userwidgets/model/pull/34
(version for @userwidgets/model needs to be updated.)

Use ClientCollection

---

package-lock.json
package.json
src/components.d.ts
src/components/organization/picker/index.tsx
src/components/smoothly/menu-options/index.tsx
src/components/smoothly/picker/index.tsx
src/components/user/permission-update/index.tsx

* updated smoothly
* commented out currently unsupported components that  broke with the update

Updated smoothly

---

package-lock.json
package.json

updated to smoothly alpha 62

---

src/components/login/register-dialog/index.tsx
src/components/login/register-dialog/style.css

* Fix so that firefox (and maybe chrome) saves email as default username instead of name

fix email on register

---

package-lock.json
package.json
src/State/Applications.ts
src/State/Organizations.ts
src/State/Users.ts
src/components/demo/index.tsx

Update to new model and minor fix.

Model 0.5.x

---

src/components/login/index.tsx

Must use login before join. Join requires a key and key have not been acquired yet.

login before joining

---

src/components.d.ts
src/components/demo/index.tsx
src/components/demo/style.css
src/components/user/logout/index.tsx
src/components/user/logout/style.css

log out component.
The component itself aims to be easy to style by the.. end developer?

Logout component

---

package-lock.json
package.json
src/components/organization/picker/style.css

Color rework

---

src/State/Locales.ts
src/components/login/login-dialog/index.tsx
src/components/login/register-dialog/index.tsx
src/components/organization/picker/index.tsx
src/components/user/index.tsx
src/components/user/list/index.tsx
src/components/user/list/invited/index.tsx
src/components/user/set-password/index.tsx
src/components/user/status/index.tsx

* fixed: language was never set
* fixed: all subscribers to language only got undefined

language not constantly undefined

---

package-lock.json
package.json

packages contains fixes for permission property transformation on key.
* updated authy
* updated userwidgets/model

eky permission transform fix

---

src/components.d.ts

component out of sync for some reason.

componente.d.ts

---

src/components.d.ts
src/components/login/index.tsx
src/components/login/login-dialog/index.tsx
src/components/login/login-dialog/translation/sv.ts
src/components/login/translation/sv.ts

* Added "Wrong credentials" error message when entering wrong credentials to login. 
* Clears password input field when entering wrong credentials

Wrong password

---

src/State/Applications.ts
src/State/Organizations.ts
src/State/Users.ts

* set request to undefined after value is set

fix: stopped infinite loop

---

package-lock.json
package.json
src/components/user/list/invite/cell/style.css

updated smoothly to fix coloring issue on table border

smoothly update

---

package-lock.json
package.json

Fixes:
* updated `smoothly`
* updated `isoly`

fix: updated packages

---

package-lock.json
package.json
src/State/Applications.ts
src/State/Organizations.ts
src/State/Users.ts

* using lazy subscriptions internally in state
* saving current organization id in sessionstorage that is used to try to get determine the current organization on page load

lazy loading and storing org

---

package-lock.json
package.json
src/State/Users.ts
src/components/user/index.tsx
src/components/user/style.css
src/components/user/translation/sv.ts

Closes https://github.com/pax2pay/worker-banking-ledger/issues/1209

Button to disable 2fa in users table expandable cell

---

package-lock.json
package.json
src/assets/style/typography.css
src/components/demo/organization/style.css
src/components/demo/settings/style.css
src/components/user/list/invite/cell/style.css
src/components/user/list/row/index.tsx

* updated all packages
* updated CSS selectors to reflect changes in the smoothly table
* moved user list status cell to its correct place so its before custom cells. (status was under age header in demo)

updated smoothly and others

---

package-lock.json
package.json
src/components/login/login-dialog/index.tsx
src/components/login/register-dialog/index.tsx
src/components/login/two-factor-dialog/index.tsx
src/components/me/name/index.tsx
src/components/me/password/index.tsx
src/components/me/two-factor/setup/index.tsx
src/components/organization/index.tsx
src/components/user/index.tsx
src/components/user/list/invite/index.tsx

* updated smoothly
* removed all imports to `smoothly/dist/types/components` in an attempt to make `smoothly` updatable by an app depending on `userwidgets/ui` without updating `userwidgets/ui` to the exact same `smoothly` version.

Updating smoothly

---

package-lock.json
package.json
src/components/demo/index.tsx
src/components/me/menu/index.tsx
src/components/me/menu/style.css

Updated styling for me menu.
